import "./globals.css";
import localFont from "next/font/local";

const poppins = localFont({
  src: "../public/font/Poppins-Regular.ttf",
  // src:
  //   [
  //   {
  //     path: "../public/font/Poppins-Regular.ttf",
  //     weight: "400",
  //     style: "normal",
  //   },

  //   {
  //     path: "../public/font/Poppins-Bold.ttf",
  //     weight: "700",
  //     style: "normal",
  //   },
  // ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
